# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 1258)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 20)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setStyleSheet("/*background-color: qconicalgradient(cx:0.5, cy:0.5, angle:224.5, stop:0 rgba(245, 245, 245, 255), stop:0.25 rgba(245, 245, 245, 255), stop:0.251351 rgba(0, 0, 0, 0));\n"
"*/\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:224.5, stop:0 rgba(245, 245, 245, 255), stop:0.99005 rgba(245, 245, 245, 255), stop:1 rgba(0, 0, 0, 0));")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_22.setContentsMargins(14, 14, 14, 14)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_nhietdo = QtWidgets.QFrame(self.frame_9)
        self.frame_nhietdo.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 136px;")
        self.frame_nhietdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nhietdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nhietdo.setObjectName("frame_nhietdo")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_nhietdo)
        self.verticalLayout_19.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_nhietdo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"background-color: rgba(0, 0, 0, 0);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_19.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_nhietdo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"background-color: rgba(0, 0, 0, 0);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_19.addWidget(self.pushButton_34)
        self.horizontalLayout_22.addWidget(self.frame_nhietdo)
        self.horizontalLayout.addWidget(self.frame_9)
        self.frame_chart1 = QtWidgets.QFrame(self.frame_2)
        self.frame_chart1.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_chart1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart1.setObjectName("frame_chart1")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_chart1)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.scatter_chart_8 = QtWidgets.QVBoxLayout()
        self.scatter_chart_8.setObjectName("scatter_chart_8")
        self.verticalLayout_29.addLayout(self.scatter_chart_8)
        self.verticalLayout_29.setStretch(0, 5)
        self.horizontalLayout.addWidget(self.frame_chart1)
        self.frame_do_am = QtWidgets.QFrame(self.frame_2)
        self.frame_do_am.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:224.5, stop:0 rgba(245, 245, 245, 255), stop:0.25 rgba(245, 245, 245, 255), stop:0.251351 rgba(0, 0, 0, 0));\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:224.5, stop:0 rgba(245, 245, 245, 255), stop:0.99005 rgba(245, 245, 245, 255), stop:1 rgba(0, 0, 0, 0));")
        self.frame_do_am.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_do_am.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_do_am.setObjectName("frame_do_am")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_do_am)
        self.horizontalLayout_23.setContentsMargins(14, 14, 14, 14)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_40 = QtWidgets.QFrame(self.frame_do_am)
        self.frame_40.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 136px;")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_81.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_40)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"background-color: rgba(0, 0, 0, 0);")
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_81.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_40)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"background-color: rgba(0, 0, 0, 0);")
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_81.addWidget(self.pushButton_36)
        self.horizontalLayout_23.addWidget(self.frame_40)
        self.horizontalLayout.addWidget(self.frame_do_am)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_chart2 = QtWidgets.QFrame(self.frame_3)
        self.frame_chart2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_chart2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart2.setObjectName("frame_chart2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_chart2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.line_chart_2 = QtWidgets.QVBoxLayout()
        self.line_chart_2.setObjectName("line_chart_2")
        self.verticalLayout_23.addLayout(self.line_chart_2)
        self.verticalLayout_23.setStretch(0, 5)
        self.gridLayout_2.addWidget(self.frame_chart2, 0, 0, 1, 1)
        self.frame_chart3 = QtWidgets.QFrame(self.frame_3)
        self.frame_chart3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_chart3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart3.setObjectName("frame_chart3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_chart3)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.scatter_chart_5 = QtWidgets.QVBoxLayout()
        self.scatter_chart_5.setObjectName("scatter_chart_5")
        self.verticalLayout_21.addLayout(self.scatter_chart_5)
        self.verticalLayout_21.setStretch(0, 5)
        self.gridLayout_2.addWidget(self.frame_chart3, 0, 1, 1, 1)
        self.frame_chart4 = QtWidgets.QFrame(self.frame_3)
        self.frame_chart4.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_chart4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart4.setObjectName("frame_chart4")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_chart4)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.bar_chart_2 = QtWidgets.QVBoxLayout()
        self.bar_chart_2.setObjectName("bar_chart_2")
        self.verticalLayout_22.addLayout(self.bar_chart_2)
        self.verticalLayout_22.setStretch(0, 5)
        self.gridLayout_2.addWidget(self.frame_chart4, 1, 0, 1, 1)
        self.frame_chart5 = QtWidgets.QFrame(self.frame_3)
        self.frame_chart5.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_chart5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart5.setObjectName("frame_chart5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_chart5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.histogram_chart_2 = QtWidgets.QVBoxLayout()
        self.histogram_chart_2.setObjectName("histogram_chart_2")
        self.verticalLayout_20.addLayout(self.histogram_chart_2)
        self.gridLayout_2.addWidget(self.frame_chart5, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_button = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_button.setFont(font)
        self.load_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(154, 153, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"    ")
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_2.addWidget(self.load_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.start_button = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_button.setFont(font)
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(154, 153, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"    ")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.notice_label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.notice_label.setFont(font)
        self.notice_label.setObjectName("notice_label")
        self.horizontalLayout_2.addWidget(self.notice_label)
        self.help_button = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.help_button.setFont(font)
        self.help_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(154, 153, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"    ")
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_2.addWidget(self.help_button)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Data visualization app"))
        self.label_3.setText(_translate("MainWindow", "Ninh"))
        self.pushButton_33.setText(_translate("MainWindow", "Nhiệt độ"))
        self.pushButton_34.setText(_translate("MainWindow", "0°C"))
        self.pushButton_35.setText(_translate("MainWindow", "Độ ẩm"))
        self.pushButton_36.setText(_translate("MainWindow", "0%"))
        self.load_button.setText(_translate("MainWindow", "Open file"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Please input city name"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.notice_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">TextLabel</span></p></body></html>"))
        self.help_button.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
